---
- 
  name: "Install certbot"
  hosts: localhost
  tasks:
    - name: "Install certbot"
      apt:
        name: certbot
        state: present
    - name: "Install certbot nginx plugin"
      apt:
        name: python3-certbot-nginx
        state: present
        
