---
- 
  name: "Request for certificates"
  hosts: localhost
  tasks:
    # - name: "Import secrets"
    #  include_vars: secrets.yml
    - name: "Include global variables"
      include_vars: global_variables.yml
    - name: "Run certbot standalone"
      command: '/usr/bin/certbot -n --agree-tos --email {{ cert_admin_email }} run --nginx --domains {{ ssl_domains_list }}'
